version: '3.4'

services:

  java:
    ports:
      - "8080:8080"

  netfx:
    image: alpine

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"

networks:
  app-net:
