version: '3.4'

services:

  java:
    image: psmonitoring/java:v2
    networks:
      - app-net

  netfx:
    image: psmonitoring/netfx:v2
    networks:
      - app-net

  prometheus:
    image: psmonitoring/prometheus:v2.3.1
    networks:
      - app-net

  grafana:
    image: psmonitoring/grafana:5.2.1
    networks:
      - app-net

networks:
  app-net:
