global:
  scrape_interval: 10s
  external_labels:
    monitor: 'local-monitor'

scrape_configs:

  - job_name: 'netfx-app'
    metrics_path: /metrics/
    dns_sd_configs:
      - names:
        - tasks.netfx
        type: A
        port: 50506

  - job_name: 'java-app'
    metrics_path: /app-metrics/
    dns_sd_configs:
      - names:
        - tasks.java
        type: A
        port: 8080

  - job_name: 'netfx-iis'
    metrics_path: /metrics/
    dns_sd_configs:
      - names:
        - tasks.netfx
        type: A
        port: 50505

  - job_name: 'java-tomcat'
    metrics_path: /metrics/
    dns_sd_configs:
      - names:
        - tasks.java
        type: A
        port: 8080

  - job_name: 'docker-managers'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:50501']

  - job_name: 'docker-workers'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:50501']
